name: Shellcheck
on: pull_request
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run shellcheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@0.1.0
